apiVersion: v1
kind: Service
metadata:
  namespace: micro-nest-nsp
  name: auth-svc
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: micro-nest-nsp
  name: auth-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth-container
          image: micro-nest/auth
          ports:
            - containerPort: 4000
          envFrom:
            - secretRef:
                name: micro-nest-secret
          resources: 
            limits:
              memory: "512Mi"
              cpu: "0.2" 