apiVersion: v1
kind: Service
metadata:
  namespace: micro-nest-nsp
  name: gateway-svc
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: gateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: micro-nest-nsp
  name: gateway-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway-container
          image: micro-nest/gateway
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: micro-nest-secret
          resources: 
            limits:
              memory: "512Mi"
              cpu: "0.2" 