apiVersion: v1
kind: Service
metadata:
  namespace: micro-nest-nsp
  name: users-svc
spec:
  selector:
    app: users
  ports:
    - protocol: TCP
      port: 6000
      targetPort: 6000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: micro-nest-nsp
  name: users-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users-container
          image: micro-nest/users
          ports:
            - containerPort: 6000
          envFrom:
            - secretRef:
                name: micro-nest-secret
          resources: 
            limits:
              memory: 512Mi
              cpu: "0.2" 